targets:
  $default:
    builders:
      fast_drift_gen:
        enabled: true
        generate_for:
          exclude:
            - test
            - example
          include:
            - test/gen_*

builders:
  fast_drift_gen:
    target: ":fast_drift_gen"
    import: "package:fast_drift_gen/builder.dart"
    builder_factories: ["fastDrift"]
    build_extensions: {".dart": ["fast_drift_gen.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]