name: fast_drift_gen
version: 1.3.0
description: Automatically generating `Companion` and `Table` classes with `@DriftGen()` annotation.

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  analyzer: ">=2.0.0 <7.0.0"
  build: ^2.0.0
  source_gen: ^1.0.0
  drift: ^2.14.0
  fast_drift:
    git:
      url: https://github.com/VovaIdzo/fast_drift
      path: fast_drift
  meta: ^1.8.0

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ">=1.11.5 <3.0.0"
  test: ^1.20.1
  source_gen_test: ^1.0.1