name: dummy_yaml

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fast_drift:
    git:
      url: https://github.com/VovaIdzo/fast_drift
      path: fast_drift

dev_dependencies:

  fast_drift_gen:
    path: ../
#  fast_drift_gen:
#    git:
#      url: https://github.com/VovaIdzo/fast_drift
#      path: fast_drift_gen
  build_runner: ^2.3.3
